---
- hosts: all
  roles:
    - role: openmicroscopy.docker
    - role: ansible-role-docker-slack-notifier
      docker_slack_notifier_channel: "#trash"
      docker_slack_notifier_username: "Docker {{ ansible_hostname }}"
