---
# tasks file for docker-slack-notifier

- name: docker slack notifier | base directory
  become: yes
  file:
    dest: "{{ docker_slack_notifier_basedir }}"
    state: directory

# TODO: Make into a new role (copied from IDR.idr-jupyterhub)
- name: docker slack notifier | download updated virtualenv
  become: yes
  get_url:
    checksum: "sha1:995ce0fa007210ac2f10258999d06813ecdd6eeb"
    dest: "{{ docker_slack_notifier_basedir }}/virtualenv-15.1.0.tar.gz"
    url: https://pypi.python.org/packages/d4/0c/9840c08189e030873387a73b90ada981885010dd9aea134d6de30cd24cb8/virtualenv-15.1.0.tar.gz

- name: docker slack notifier | extract updated virtualenv
  become: yes
  unarchive:
    creates: "{{ docker_slack_notifier_basedir }}/virtualenv-15.1.0/virtualenv.py"
    dest: "{{ docker_slack_notifier_basedir }}"
    remote_src: True
    src: "{{ docker_slack_notifier_basedir }}/virtualenv-15.1.0.tar.gz"

- name: docker slack notifier | setup virtualenv
  become: yes
  pip:
    name:
    - docker
    - pyyaml
    state: present
    virtualenv: "{{ docker_slack_notifier_basedir }}/venv"
    virtualenv_command: "{{ docker_slack_notifier_basedir }}/virtualenv-15.1.0/virtualenv.py"

- name: docker slack notifier | script
  become: yes
  copy:
    dest: "{{ docker_slack_notifier_basedir }}/docker-slack-notifier.py"
    force: yes
    src: docker-slack-notifier.py
    mode: 0555
  notify:
  - restart docker-slack-notifier

- name: docker slack notifier | systemd service
  become: yes
  template:
    dest: /etc/systemd/system/docker-slack-notifier.service
    force: yes
    src: systemd-system-docker-slack-notifier-service.j2
  notify:
  - reload systemd
  - restart docker-slack-notifier

- name: docker slack notifier | configuration file
  become: yes
  template:
    dest: "{{ docker_slack_notifier_basedir }}/docker-slack-notifier.yml"
    force: yes
    src: docker-slack-notifier-yml.j2
  notify:
  - restart docker-slack-notifier

# Flush handlers to ensure systemd is reloaded
- name: docker slack notifier | flush systemd handlers
  meta: flush_handlers

- name: docker slack notifier | enable and start server systemd
  become: yes
  service:
    enabled: yes
    name: docker-slack-notifier.service
    state: started
