---
# handlers file for ansible-role-docker-slack-notifier

- name: reload systemd
  become: yes
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: restart docker-slack-notifier
  become: yes
  service:
    name: docker-slack-notifier
    state: restarted
